language: c

git:
  depth: false
  
before_install:
  - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$OS_FOLDER
script:
  - mkdir out && cd out
  - cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
  - make -j$(nproc)

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      env:
        - OS_FOLDER=mac
      after_success:
        - tar -cvzf tic80.tar.gz --directory=$HOME/build/schraf/TIC-80/out/bin tic80.app
        - curl --retry 3 --ftp-create-dirs -T tic80.tar.gz $BUILDS_SERVER_PATH/

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - libgtk-3-dev
            - libasound2-dev
      env:
        - OS_FOLDER=linux
      after_success:
        - tar -cvzf tic80.tar.gz --directory=$HOME/build/schraf/TIC-80/out/bin tic80
        - curl --retry 3 --ftp-create-dirs -T tic80.tar.gz $BUILDS_SERVER_PATH/

    - os: linux
      language: android
      env:
        - OS_FOLDER=android
      install:
        - wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
        - unzip android-ndk-r18b-linux-x86_64.zip -d $HOME
        - export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
        - touch $HOME/.android/repositories.cfg
        - yes | sdkmanager "platforms;android-26"
        - yes | sdkmanager "build-tools;28.0.3"

      script:
        - cd build/android
        - ./gradlew assembleRelease

      after_success:
        - cp app/build/outputs/apk/universal/release/app-universal-release.apk tic80.apk
        - curl --retry 3 --ftp-create-dirs -T tic80.apk $BUILDS_SERVER_PATH/
